[2023-11-30T13:59:44.952+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-11-30T08:57:37.347573+00:00 [queued]>
[2023-11-30T13:59:44.992+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-11-30T08:57:37.347573+00:00 [queued]>
[2023-11-30T13:59:44.995+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-30T13:59:45.108+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 08:57:37.347573+00:00
[2023-11-30T13:59:45.156+0500] {standard_task_runner.py:57} INFO - Started process 28373 to run task
[2023-11-30T13:59:45.228+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-11-30T08:57:37.347573+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpebk58_9i']
[2023-11-30T13:59:45.263+0500] {standard_task_runner.py:85} INFO - Job 56: Subtask train_model
[2023-11-30T13:59:46.451+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-11-30T08:57:37.347573+00:00 [running]> on host mlops
[2023-11-30T13:59:47.660+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T08:57:37.347573+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T08:57:37.347573+00:00'
[2023-11-30T13:59:47.709+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T13:59:47.746+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/train_model.py']
[2023-11-30T13:59:47.827+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T14:00:10.814+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T14:00:10.816+0500] {subprocess.py:93} INFO - 
[2023-11-30T14:00:10.816+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T14:00:10.817+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T14:00:10.817+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T14:00:10.817+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T14:00:10.817+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T14:00:10.818+0500] {subprocess.py:93} INFO - Successfully registered model 'lr'.
[2023-11-30T14:00:10.818+0500] {subprocess.py:93} INFO - 2023/11/30 14:00:10 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: lr, version 1
[2023-11-30T14:00:10.875+0500] {subprocess.py:93} INFO - Created version '1' of model 'lr'.
[2023-11-30T14:00:10.912+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-30T14:00:10.913+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/scripts/train_model.py", line 25, in <module>
[2023-11-30T14:00:10.913+0500] {subprocess.py:93} INFO -     model.fit(df['id'].values.reshape(-1,1), df['counts'])
[2023-11-30T14:00:10.914+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
[2023-11-30T14:00:10.914+0500] {subprocess.py:93} INFO -     return fit_method(estimator, *args, **kwargs)
[2023-11-30T14:00:10.914+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 348, in fit
[2023-11-30T14:00:10.914+0500] {subprocess.py:93} INFO -     X, y = self._validate_data(
[2023-11-30T14:00:10.915+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
[2023-11-30T14:00:10.915+0500] {subprocess.py:93} INFO -     X, y = check_X_y(X, y, **check_params)
[2023-11-30T14:00:10.915+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
[2023-11-30T14:00:10.915+0500] {subprocess.py:93} INFO -     X = check_array(
[2023-11-30T14:00:10.915+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 915, in check_array
[2023-11-30T14:00:10.916+0500] {subprocess.py:93} INFO -     array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
[2023-11-30T14:00:10.916+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 380, in _asarray_with_order
[2023-11-30T14:00:10.916+0500] {subprocess.py:93} INFO -     array = numpy.asarray(array, order=order, dtype=dtype)
[2023-11-30T14:00:10.916+0500] {subprocess.py:93} INFO - ValueError: could not convert string to float: 'UCKWaEZ-_VweaEx1j62do_vQ'
[2023-11-30T14:00:11.998+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-30T14:00:12.310+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/akashy/staidg/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-30T14:00:12.384+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231130T085737, start_date=20231130T085944, end_date=20231130T090012
[2023-11-30T14:00:12.562+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 56 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 28373)
[2023-11-30T14:00:12.689+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T14:00:12.876+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
