[2023-11-30T14:05:27.981+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-11-30T08:57:37.347573+00:00 [queued]>
[2023-11-30T14:05:28.060+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2023-11-30T08:57:37.347573+00:00 [queued]>
[2023-11-30T14:05:28.062+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-30T14:05:28.196+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-30 08:57:37.347573+00:00
[2023-11-30T14:05:28.316+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2023-11-30T08:57:37.347573+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpqaom4uch']
[2023-11-30T14:05:28.322+0500] {standard_task_runner.py:85} INFO - Job 57: Subtask train_model
[2023-11-30T14:05:28.262+0500] {standard_task_runner.py:57} INFO - Started process 29760 to run task
[2023-11-30T14:05:29.523+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2023-11-30T08:57:37.347573+00:00 [running]> on host mlops
[2023-11-30T14:05:31.245+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T08:57:37.347573+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T08:57:37.347573+00:00'
[2023-11-30T14:05:31.267+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T14:05:31.279+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/train_model.py']
[2023-11-30T14:05:31.513+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T14:05:37.122+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T14:05:37.124+0500] {subprocess.py:93} INFO - 
[2023-11-30T14:05:37.133+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T14:05:37.139+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T14:05:37.145+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T14:05:37.152+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T14:05:37.173+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T14:05:37.185+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-30T14:05:37.198+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/scripts/train_model.py", line 25, in <module>
[2023-11-30T14:05:37.210+0500] {subprocess.py:93} INFO -     model.fit(df['id'].values.reshape(-1,1), df['counts'])
[2023-11-30T14:05:37.219+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/base.py", line 1152, in wrapper
[2023-11-30T14:05:37.226+0500] {subprocess.py:93} INFO -     return fit_method(estimator, *args, **kwargs)
[2023-11-30T14:05:37.504+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 348, in fit
[2023-11-30T14:05:37.504+0500] {subprocess.py:93} INFO -     X, y = self._validate_data(
[2023-11-30T14:05:37.505+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/base.py", line 622, in _validate_data
[2023-11-30T14:05:37.522+0500] {subprocess.py:93} INFO -     X, y = check_X_y(X, y, **check_params)
[2023-11-30T14:05:37.522+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1146, in check_X_y
[2023-11-30T14:05:37.523+0500] {subprocess.py:93} INFO -     X = check_array(
[2023-11-30T14:05:37.523+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/utils/validation.py", line 915, in check_array
[2023-11-30T14:05:37.524+0500] {subprocess.py:93} INFO -     array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
[2023-11-30T14:05:37.525+0500] {subprocess.py:93} INFO -   File "/home/akashy/staidg/env/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 380, in _asarray_with_order
[2023-11-30T14:05:37.699+0500] {subprocess.py:93} INFO -     array = numpy.asarray(array, order=order, dtype=dtype)
[2023-11-30T14:05:37.712+0500] {subprocess.py:93} INFO - ValueError: could not convert string to float: 'UCKWaEZ-_VweaEx1j62do_vQ'
[2023-11-30T14:05:38.952+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-30T14:05:39.229+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/akashy/staidg/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-30T14:05:39.238+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20231130T085737, start_date=20231130T090527, end_date=20231130T090539
[2023-11-30T14:05:39.368+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 29760)
[2023-11-30T14:05:39.636+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T14:05:40.318+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
