[2023-11-30T13:57:48.131+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-11-30T08:57:37.347573+00:00 [queued]>
[2023-11-30T13:57:48.151+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data manual__2023-11-30T08:57:37.347573+00:00 [queued]>
[2023-11-30T13:57:48.155+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-30T13:57:48.203+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-30 08:57:37.347573+00:00
[2023-11-30T13:57:48.225+0500] {standard_task_runner.py:57} INFO - Started process 27907 to run task
[2023-11-30T13:57:48.228+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'manual__2023-11-30T08:57:37.347573+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp6_9mingl']
[2023-11-30T13:57:48.236+0500] {standard_task_runner.py:85} INFO - Job 53: Subtask get_data
[2023-11-30T13:57:48.619+0500] {task_command.py:416} INFO - Running <TaskInstance: youtube_comments_score.get_data manual__2023-11-30T08:57:37.347573+00:00 [running]> on host mlops
[2023-11-30T13:57:49.122+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='youtube_comments_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T08:57:37.347573+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T08:57:37.347573+00:00'
[2023-11-30T13:57:49.127+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T13:57:49.135+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/akashy/staidg/scripts/get_data.py']
[2023-11-30T13:57:49.187+0500] {subprocess.py:86} INFO - Output:
[2023-11-30T13:58:58.345+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-30T13:58:58.347+0500] {subprocess.py:93} INFO - 
[2023-11-30T13:58:58.347+0500] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-30T13:58:58.347+0500] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-30T13:58:58.348+0500] {subprocess.py:93} INFO - /home/akashy/staidg/env/lib/python3.8/site-packages/pydantic/_internal/_config.py:321: UserWarning: Valid config keys have changed in V2:
[2023-11-30T13:58:58.348+0500] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-30T13:58:58.348+0500] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-30T13:58:59.131+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-30T13:58:59.369+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=youtube_comments_score, task_id=get_data, execution_date=20231130T085737, start_date=20231130T085748, end_date=20231130T085859
[2023-11-30T13:58:59.501+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-30T13:58:59.615+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
